/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ImprintRouteImport } from './routes/imprint'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsGermanGradeCalculatorRouteImport } from './routes/tools.german-grade-calculator'
import { Route as GuidesWorkStudentRouteImport } from './routes/guides.work-student'
import { Route as GuidesUniAssistRouteImport } from './routes/guides.uni-assist'
import { Route as GuidesStudentVisaRouteImport } from './routes/guides.student-visa'
import { Route as GuidesBlockedAccountRouteImport } from './routes/guides.blocked-account'
import { Route as GuidesApsCertificateRouteImport } from './routes/guides.aps-certificate'
import { Route as GuidesApplicationTimelineRouteImport } from './routes/guides.application-timeline'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ImprintRoute = ImprintRouteImport.update({
  id: '/imprint',
  path: '/imprint',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsGermanGradeCalculatorRoute =
  ToolsGermanGradeCalculatorRouteImport.update({
    id: '/tools/german-grade-calculator',
    path: '/tools/german-grade-calculator',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuidesWorkStudentRoute = GuidesWorkStudentRouteImport.update({
  id: '/guides/work-student',
  path: '/guides/work-student',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesUniAssistRoute = GuidesUniAssistRouteImport.update({
  id: '/guides/uni-assist',
  path: '/guides/uni-assist',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesStudentVisaRoute = GuidesStudentVisaRouteImport.update({
  id: '/guides/student-visa',
  path: '/guides/student-visa',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesBlockedAccountRoute = GuidesBlockedAccountRouteImport.update({
  id: '/guides/blocked-account',
  path: '/guides/blocked-account',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesApsCertificateRoute = GuidesApsCertificateRouteImport.update({
  id: '/guides/aps-certificate',
  path: '/guides/aps-certificate',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesApplicationTimelineRoute =
  GuidesApplicationTimelineRouteImport.update({
    id: '/guides/application-timeline',
    path: '/guides/application-timeline',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/imprint': typeof ImprintRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/guides/application-timeline': typeof GuidesApplicationTimelineRoute
  '/guides/aps-certificate': typeof GuidesApsCertificateRoute
  '/guides/blocked-account': typeof GuidesBlockedAccountRoute
  '/guides/student-visa': typeof GuidesStudentVisaRoute
  '/guides/uni-assist': typeof GuidesUniAssistRoute
  '/guides/work-student': typeof GuidesWorkStudentRoute
  '/tools/german-grade-calculator': typeof ToolsGermanGradeCalculatorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/imprint': typeof ImprintRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/guides/application-timeline': typeof GuidesApplicationTimelineRoute
  '/guides/aps-certificate': typeof GuidesApsCertificateRoute
  '/guides/blocked-account': typeof GuidesBlockedAccountRoute
  '/guides/student-visa': typeof GuidesStudentVisaRoute
  '/guides/uni-assist': typeof GuidesUniAssistRoute
  '/guides/work-student': typeof GuidesWorkStudentRoute
  '/tools/german-grade-calculator': typeof ToolsGermanGradeCalculatorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/imprint': typeof ImprintRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/guides/application-timeline': typeof GuidesApplicationTimelineRoute
  '/guides/aps-certificate': typeof GuidesApsCertificateRoute
  '/guides/blocked-account': typeof GuidesBlockedAccountRoute
  '/guides/student-visa': typeof GuidesStudentVisaRoute
  '/guides/uni-assist': typeof GuidesUniAssistRoute
  '/guides/work-student': typeof GuidesWorkStudentRoute
  '/tools/german-grade-calculator': typeof ToolsGermanGradeCalculatorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/imprint'
    | '/privacy'
    | '/terms'
    | '/guides/application-timeline'
    | '/guides/aps-certificate'
    | '/guides/blocked-account'
    | '/guides/student-visa'
    | '/guides/uni-assist'
    | '/guides/work-student'
    | '/tools/german-grade-calculator'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/imprint'
    | '/privacy'
    | '/terms'
    | '/guides/application-timeline'
    | '/guides/aps-certificate'
    | '/guides/blocked-account'
    | '/guides/student-visa'
    | '/guides/uni-assist'
    | '/guides/work-student'
    | '/tools/german-grade-calculator'
  id:
    | '__root__'
    | '/'
    | '/imprint'
    | '/privacy'
    | '/terms'
    | '/guides/application-timeline'
    | '/guides/aps-certificate'
    | '/guides/blocked-account'
    | '/guides/student-visa'
    | '/guides/uni-assist'
    | '/guides/work-student'
    | '/tools/german-grade-calculator'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ImprintRoute: typeof ImprintRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  GuidesApplicationTimelineRoute: typeof GuidesApplicationTimelineRoute
  GuidesApsCertificateRoute: typeof GuidesApsCertificateRoute
  GuidesBlockedAccountRoute: typeof GuidesBlockedAccountRoute
  GuidesStudentVisaRoute: typeof GuidesStudentVisaRoute
  GuidesUniAssistRoute: typeof GuidesUniAssistRoute
  GuidesWorkStudentRoute: typeof GuidesWorkStudentRoute
  ToolsGermanGradeCalculatorRoute: typeof ToolsGermanGradeCalculatorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imprint': {
      id: '/imprint'
      path: '/imprint'
      fullPath: '/imprint'
      preLoaderRoute: typeof ImprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/german-grade-calculator': {
      id: '/tools/german-grade-calculator'
      path: '/tools/german-grade-calculator'
      fullPath: '/tools/german-grade-calculator'
      preLoaderRoute: typeof ToolsGermanGradeCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/work-student': {
      id: '/guides/work-student'
      path: '/guides/work-student'
      fullPath: '/guides/work-student'
      preLoaderRoute: typeof GuidesWorkStudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/uni-assist': {
      id: '/guides/uni-assist'
      path: '/guides/uni-assist'
      fullPath: '/guides/uni-assist'
      preLoaderRoute: typeof GuidesUniAssistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/student-visa': {
      id: '/guides/student-visa'
      path: '/guides/student-visa'
      fullPath: '/guides/student-visa'
      preLoaderRoute: typeof GuidesStudentVisaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/blocked-account': {
      id: '/guides/blocked-account'
      path: '/guides/blocked-account'
      fullPath: '/guides/blocked-account'
      preLoaderRoute: typeof GuidesBlockedAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/aps-certificate': {
      id: '/guides/aps-certificate'
      path: '/guides/aps-certificate'
      fullPath: '/guides/aps-certificate'
      preLoaderRoute: typeof GuidesApsCertificateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/application-timeline': {
      id: '/guides/application-timeline'
      path: '/guides/application-timeline'
      fullPath: '/guides/application-timeline'
      preLoaderRoute: typeof GuidesApplicationTimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ImprintRoute: ImprintRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  GuidesApplicationTimelineRoute: GuidesApplicationTimelineRoute,
  GuidesApsCertificateRoute: GuidesApsCertificateRoute,
  GuidesBlockedAccountRoute: GuidesBlockedAccountRoute,
  GuidesStudentVisaRoute: GuidesStudentVisaRoute,
  GuidesUniAssistRoute: GuidesUniAssistRoute,
  GuidesWorkStudentRoute: GuidesWorkStudentRoute,
  ToolsGermanGradeCalculatorRoute: ToolsGermanGradeCalculatorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
